# Generated by Django 4.2.19 on 2025-02-08 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userApp', '0001_initial'),
        ('quizApp', '0001_initial'),
        ('dictApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.customuser'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='dictApp.word'),
        ),
    ]
