# Generated by Django 4.2.19 on 2025-02-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0004_alter_quizattempt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='totalScore',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
