# Generated by Django 4.2.19 on 2025-02-17 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0005_quizattempt_totalscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quizattempt',
            old_name='totalScore',
            new_name='maxScore',
        ),
    ]
