# Generated by Django 4.2.19 on 2025-02-17 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0001_initial'),
        ('quizApp', '0006_rename_totalscore_quizattempt_maxscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizattempt',
            name='word',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dictApp.word'),
        ),
    ]
