# Generated by Django 4.2.19 on 2025-02-22 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0002_idiom'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizApp', '0007_alter_quizattempt_word'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdiomMCQ',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('option_a', models.CharField(max_length=255)),
                ('option_b', models.CharField(max_length=255)),
                ('option_c', models.CharField(max_length=255)),
                ('option_d', models.CharField(max_length=255)),
                ('correct_option', models.CharField(choices=[('A', 'Option A'), ('B', 'Option B'), ('C', 'Option C'), ('D', 'Option D')], max_length=1)),
                ('explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idiom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mcqs', to='dictApp.idiom')),
            ],
        ),
    ]
