# Generated by Django 4.2.19 on 2025-02-25 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0001_initial'),
        ('quizApp', '0008_idiommcq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiommcq',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userApp.customuser'),
        ),
    ]
