# Generated by Django 4.2.19 on 2025-02-26 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0009_alter_idiommcq_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idiommcq',
            name='explanation',
        ),
    ]
