# Generated by Django 4.2.19 on 2025-02-26 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0010_remove_idiommcq_explanation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idiommcq',
            old_name='option_a',
            new_name='option1',
        ),
        migrations.RenameField(
            model_name='idiommcq',
            old_name='option_b',
            new_name='option2',
        ),
        migrations.RenameField(
            model_name='idiommcq',
            old_name='option_c',
            new_name='option3',
        ),
        migrations.RenameField(
            model_name='idiommcq',
            old_name='option_d',
            new_name='option4',
        ),
    ]
