# Generated by Django 4.2.19 on 2025-02-26 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0011_rename_option_a_idiommcq_option1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idiommcq',
            old_name='question',
            new_name='question_text',
        ),
    ]
