# Generated by Django 4.2.19 on 2025-02-26 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizApp', '0012_rename_question_idiommcq_question_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idiommcq',
            name='correct_option',
            field=models.CharField(choices=[(1, 'Option 1'), (2, 'Option 2'), (3, 'Option 3'), (4, 'Option 4')], max_length=1),
        ),
    ]
