# Generated by Django 4.2.19 on 2025-02-22 17:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dictApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idiom',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phrase', models.CharField(max_length=255, unique=True)),
                ('meaning', models.TextField(blank=True, null=True)),
                ('example', models.TextField(blank=True, null=True)),
                ('insights', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('origin', models.TextField(blank=True, null=True)),
                ('difficulty_level', models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], default='Beginner', max_length=20)),
                ('tags', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('related_idioms', models.ManyToManyField(blank=True, to='dictApp.idiom')),
            ],
        ),
    ]
