# Generated by Django 4.2.19 on 2025-02-26 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictApp', '0002_idiom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idiom',
            name='related_idioms',
        ),
        migrations.AddField(
            model_name='idiom',
            name='related_idioms',
            field=models.TextField(blank=True, null=True),
        ),
    ]
